//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkedinClient.LService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LService.linkedinServicedata")]
    public interface linkedinServicedata {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/linkedinServicedata/linkedinProfile", ReplyAction="http://tempuri.org/linkedinServicedata/linkedinProfileResponse")]
        string linkedinProfile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/linkedinServicedata/linkedinProfile", ReplyAction="http://tempuri.org/linkedinServicedata/linkedinProfileResponse")]
        System.Threading.Tasks.Task<string> linkedinProfileAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface linkedinServicedataChannel : LinkedinClient.LService.linkedinServicedata, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class linkedinServicedataClient : System.ServiceModel.ClientBase<LinkedinClient.LService.linkedinServicedata>, LinkedinClient.LService.linkedinServicedata {
        
        public linkedinServicedataClient() {
        }
        
        public linkedinServicedataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public linkedinServicedataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public linkedinServicedataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public linkedinServicedataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string linkedinProfile() {
            return base.Channel.linkedinProfile();
        }
        
        public System.Threading.Tasks.Task<string> linkedinProfileAsync() {
            return base.Channel.linkedinProfileAsync();
        }
    }
}
